/** Portal-neutral analytics boundary. CrazyGames dashboard is the release-one transport. */
export const GOAL = { bootComplete: 'boot_complete', bootFailed: 'boot_failed', firstCaseStart: 'first_case_start', firstCaseComplete: 'first_case_complete', caseComplete: 'case_complete', rewardedComplete: 'rewarded_complete', caseStart: 'case_start', investigationInterrupt: 'investigation_interrupt', investigationResume: 'investigation_resume', evidenceView: 'evidence_view', evidenceStamp: 'evidence_stamp', evidenceAnalysisStart: 'evidence_analysis_start', evidenceAnalysisHint: 'evidence_analysis_hint', evidenceAnalysisComplete: 'evidence_analysis_complete', onboardingComplete: 'onboarding_complete', finalSynthesisComplete: 'final_synthesis_complete', finalSynthesisSkip: 'final_synthesis_skip', hintBuy: 'hint_buy', verdictSubmit: 'verdict_submit', rewardDouble: 'reward_double', fundsRestore: 'funds_restore', achievement: 'achievement_unlock', rankUp: 'rank_up', bankruptcy: 'bankruptcy', dailyClaim: 'daily_claim', dailyAdUnlock: 'daily_ad_unlock', adOffer: 'ad_offer', adAccept: 'ad_accept', adOpen: 'ad_open', adClose: 'ad_close', adReward: 'ad_reward', adError: 'ad_error', serviceView: 'service_view', serviceSelect: 'service_select', serviceBuy: 'service_buy', serviceUse: 'service_use', shopView: 'shop_view', productView: 'product_view', purchaseStart: 'purchase_start', purchaseSuccess: 'purchase_success', purchaseError: 'purchase_error', purchaseRestore: 'purchase_restore', rejectBlocked: 'reject_blocked', budgetExhausted: 'budget_exhausted', lockedCaseClick: 'locked_case_click', tabSwitch: 'tab_switch' } as const;
export type GoalName = (typeof GOAL)[keyof typeof GOAL];
let activeSince = Date.now(); let activeTotal = 0; let adPaused = false;
export const initAnalytics = () => { activeSince = Date.now(); };
export const trackGoal = (_name: GoalName, _params?: Record<string, unknown>) => {};
export const trackEvent = (_name: string, _params?: Record<string, unknown>) => {};
export const setAnalyticsContext = (_params: Record<string, unknown>) => {};
export const setUserParams = (_params: Record<string, unknown>) => {};
export const setAnalyticsAdPaused = (paused: boolean) => { if (paused && !adPaused) activeTotal += Date.now() - activeSince; if (!paused && adPaused) activeSince = Date.now(); adPaused = paused; };
export const getAnalyticsActiveTotalMs = () => activeTotal + (adPaused ? 0 : Date.now() - activeSince);
